apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest
      version: canary
  template:
    metadata:
      labels:
        app: aceest
        version: canary
    spec:
      containers:
        - name: aceest-container
          image: sarath93636/aceest-gym:v2.0
          ports:
            - containerPort: 5000
